//#define TINYGLTF_IMPLEMENTATION
//#define TINYGLTF_NO_STB_IMAGE
//#define TINYGLTF_NO_STB_IMAGE_WRITE
//#define TINYGLTF_NO_INCLUDE_STB_IMAGE
//#define TINYGLTF_NO_INCLUDE_STB_IMAGE_WRITE 
//#define TINYGLTF_NO_EXTERNAL_IMAGE

#define TINYGLTF_IMPLEMENTATION
#define STB_IMAGE_WRITE_IMPLEMENTATION
#include <TinyGLTF/tiny_gltf.h>